version: '2.14.0'

services:
  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=pet_store_database
      - MYSQL_USER=pet_store_user
      - MYSQL_PASSWORD=dummypassword
